# Generated by Django 2.0.7 on 2018-07-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20180721_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(default='asdf@asdf.com', max_length=254),
        ),
    ]
